### ISSUE TITLE
Update the ScopeTemplate Controller to address simple CRUD events

### ISSUE THREAD

**Issue by awgreene** [awgreene/oria-operator#1]
**Goal:** Basic CRUD events are supported by the `ScopeTemplate` controller.
**Acceptance Criteria:**
- Creating a `ScopeTemplate` CR creates a `ClusterRole` if a scopeInstance references the scopeTemplate.
- Creating a `ScopeTemplate` CR does not create a `ClusterRole` if a scopeInstance does not reference the scopeTemplate.
- Updating a `ScopeTemplate` CR to change an existing `spec.ClusterRole[*]` changes the associated`ClusterRoles`.
- Updating a `ScopeTemplate` CR to include an additional `spec.ClusterRole[*]` entry creates a new `ClusterRole`.
- Updating a `ScopeTemplate` CR to remove an a `spec.ClusterRole[*]` entry deletes the associated `ClusterRole`.
- Deleting the `ScopeTemplate` CR removes all of the `ClusterRoles` it created.  I suggest using [OwnerReferences](https://kubernetes.io/docs/concepts/overview/working-with-objects/owners-dependents/#owner-references-in-object-specifications).

**Comment by laxmikantbpandhare** [comment]
@awgreene we can close this as we fixed this already.
