### ISSUE TITLE
Use GenerateName and Labels to create clusterRoles and (cluster)RoleBindings

### ISSUE THREAD

**Issue by awgreene** [awgreene/oria-operator#5]
**Goal:** RBAC generated by the oria-operator should not have hardcoded, static names.

**Acceptance Criteria**:
- ClusterRoles created by the ScopeTemplate controller have a labeled
- (cluster)RoleBindings created by the ScopeInstance controller have are labeled
- The labels used to identify resources created by the ScopeTemplate and ScopeInstance controllers must have a static KEY and a VALUE that uniquely identifies the ScopeTemplate/ScopeInstance CR.
- The labels must adhere to the naming requirements found here: https://kubernetes.io/docs/concepts/overview/working-with-objects/labels/#syntax-and-character-set

**Comment by laxmikantbpandhare** [comment]
This is fixed now. We added labels and GeneratedName while creating ClusterRole, ClusterRoleBinding, and RoleBindings.

**Comment by laxmikantbpandhare** [comment]
@awgreene - We can close this issue.

**Comment by awgreene** [comment]
Completed in #12 and #14.
